version: "3"
services: 
    mymongo_wiki:
        image: "mongo"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: test123
            MONGO_INITDB_DATABASE: mindtasticWiki

    myreader:
        build: .
        volumes:
          - .:/app
        depends_on: 
            - mymongo_wiki
        ports:
            - "5001:5001"