version: "3"
services: 
    mymongo_wiki:
        image: "mongo"
    
    myreader:
        build: .
        volumes:
          - .:/app
        depends_on: 
            - mymongo_wiki
        ports:
            - "5001:5001"